# Generated by Django 2.2.13 on 2020-06-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200618_0803'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fjhgjhg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mnhgjhji', models.BigIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='ftghryuj5y',
        ),
        migrations.RemoveField(
            model_name='customtext',
            name='sfasdfasz',
        ),
        migrations.RemoveField(
            model_name='ghvhggfgvcafvwse',
            name='sdfaef',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='werqwrf',
        ),
    ]
